services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ishan
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
